CREATE TABLE buildingentries
(
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TIMESTAMP" TIMESTAMP,
    action VARCHAR2(20),
    username VARCHAR2(20),
    enabled NUMBER(1)
)
