/*
 * QALIPSIS
 * Copyright (C) 2025 AERIS IT Solutions GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package io.qalipsis.plugins.netty.socket

import io.qalipsis.api.context.StepContext
import io.qalipsis.api.context.StepName
import io.qalipsis.api.events.EventsLogger
import io.qalipsis.api.meters.CampaignMeterRegistry
import io.qalipsis.api.retry.RetryPolicy
import io.qalipsis.api.steps.AbstractStep
import io.qalipsis.plugins.netty.RequestBuilder
import io.qalipsis.plugins.netty.RequestResult
import io.qalipsis.plugins.netty.monitoring.StepContextBasedSocketMonitoringCollector

/**
 * Parent class of steps executing requests using [SocketClient]s created by other steps.
 *
 * @param I type of the input of the step
 * @param O type of the output of the step
 * @param REQ type of the request processed by the client (and generated from I)
 * @param RES type of the response generated by the client (and later converted to O)
 * @param OWNER type of the step that owns the client
 *
 * @author Eric Jessé
 */
internal abstract class QuerySocketClientStep<I, O : Any, REQ : Any, RES : Any, REQ_BUILDER : RequestBuilder<REQ>, OWNER : SocketClientStep<*, REQ, RES, *>>(
    id: StepName,
    retryPolicy: RetryPolicy?,
    val connectionOwner: OWNER,
    private val stepQualifier: String,
    private val requestBuilder: REQ_BUILDER,
    private val requestFactory: suspend REQ_BUILDER.(StepContext<*, *>, I) -> REQ,
    private val eventsLogger: EventsLogger?,
    private val meterRegistry: CampaignMeterRegistry?
) : AbstractStep<I, RequestResult<I, O, *>>(id, retryPolicy) {

    override suspend fun execute(context: StepContext<I, RequestResult<I, O, *>>) {
        val monitoringCollector =
            createMonitoringCollector(context)
        val input = context.receive()
        try {
            val result = connectionOwner.execute(
                monitoringCollector,
                context,
                input,
                requestBuilder.requestFactory(context, input)
            )
            context.send(monitoringCollector.toResult(input, convertResponseToOutput(result), null))
        } catch (e: SocketRequestException) {
            throw e
        } catch (e: SocketException) {
            throw SocketRequestException(
                RequestResult(
                    e.result.sendingFailure,
                    e.result.failure,
                    input,
                    e.result.response,
                    e.result.meters
                )
            )
        } catch (e: Exception) {
            throw SocketRequestException(
                RequestResult(
                    monitoringCollector.sendingFailure,
                    e.takeUnless { it == monitoringCollector.sendingFailure },
                    input,
                    null,
                    monitoringCollector.meters
                )
            )
        }
    }

    /**
     * Converts the response from the client into the output of the step.
     */
    @Suppress("UNCHECKED_CAST")
    open fun convertResponseToOutput(response: RES): O = response as O

    protected open fun createMonitoringCollector(context: StepContext<I, RequestResult<I, O, *>>) =
        StepContextBasedSocketMonitoringCollector(context, eventsLogger, meterRegistry, stepQualifier)


}
