/*
 * QALIPSIS
 * Copyright (C) 2025 AERIS IT Solutions GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package io.qalipsis.plugins.netty.socket

import io.netty.channel.EventLoopGroup
import io.qalipsis.api.context.MinionId
import io.qalipsis.api.context.StepContext
import io.qalipsis.api.context.StepName
import io.qalipsis.api.context.StepStartStopContext
import io.qalipsis.api.events.EventsLogger
import io.qalipsis.api.lang.tryAndLogOrNull
import io.qalipsis.api.logging.LoggerHelper.logger
import io.qalipsis.api.meters.CampaignMeterRegistry
import io.qalipsis.api.retry.RetryPolicy
import io.qalipsis.api.steps.AbstractStep
import io.qalipsis.plugins.netty.EventLoopGroupSupplier
import io.qalipsis.plugins.netty.RequestBuilder
import io.qalipsis.plugins.netty.monitoring.StepBasedTcpMonitoringCollector
import io.qalipsis.plugins.netty.monitoring.StepContextBasedSocketMonitoringCollector
import io.qalipsis.plugins.netty.tcp.ConnectionAndRequestResult
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.LinkedBlockingQueue

/**
 * Parent class of steps using implementations of [SocketClient]s that are pre-created at start and
 * assigned to individual minions on first access.
 *
 * This follows the WARMUP connection strategy pattern: all connections are established eagerly during
 * [start], and each minion is assigned a pre-warmed connection on its first [execute] call.
 *
 * @param I type of the input of the step
 * @param O type of the output of the step
 * @param CONF type of the configuration of the client
 * @param REQ type of the request processed by the client (and generated from I)
 * @param RES type of the response generated by the client (and later converted to O)
 * @param CLI type of the client
 *
 * @author Eric Jesse
 */
internal abstract class WarmupSocketClientStep<I, O : Any, CONF : SocketClientConfiguration, REQ : Any, RES : Any, REQ_BUILDER : RequestBuilder<REQ>, CLI : SocketClient<CONF, REQ, RES, CLI>>(
    id: StepName,
    retryPolicy: RetryPolicy?,
    private val requestBuilder: REQ_BUILDER,
    private val requestFactory: suspend REQ_BUILDER.(StepContext<*, *>, I) -> REQ,
    private val configuration: CONF,
    private val shared: Boolean,
    private val stepQualifier: String,
    private val eventLoopGroupSupplier: EventLoopGroupSupplier,
    private val eventsLogger: EventsLogger?,
    private val meterRegistry: CampaignMeterRegistry?,
) : AbstractStep<I, ConnectionAndRequestResult<I, O>>(id, retryPolicy),
    SocketClientStep<I, REQ, RES, ConnectionAndRequestResult<I, O>> {

    private var running = false

    protected lateinit var workerGroup: EventLoopGroup

    private lateinit var stepMonitoringCollector: StepBasedTcpMonitoringCollector

    /**
     * Queue of pre-created clients ready for assignment to minions.
     */
    private lateinit var preparedClients: LinkedBlockingQueue<CLI>

    /**
     * Maps each minion to its assigned pre-warmed client.
     */
    private val assignedClients = ConcurrentHashMap<MinionId, CLI>()

    override suspend fun start(context: StepStartStopContext) {
        workerGroup = eventLoopGroupSupplier.getGroup()
        stepMonitoringCollector = StepBasedTcpMonitoringCollector(eventsLogger, meterRegistry, context, stepQualifier)
        running = true

        val minionCount = context.scheduledMinionCount
        preparedClients = LinkedBlockingQueue(minionCount)
        repeat(minionCount) {
            preparedClients.put(createClient(workerGroup, stepMonitoringCollector))
        }
        log.debug { "Pre-created $minionCount clients for warmup step $name" }
    }

    /**
     * Creates a new client to be added to the pre-warmed pool.
     */
    internal abstract suspend fun createClient(
        workerGroup: EventLoopGroup,
        monitoringCollector: StepBasedTcpMonitoringCollector,
    ): CLI

    override suspend fun execute(context: StepContext<I, ConnectionAndRequestResult<I, O>>) {
        val monitoringCollector = createMonitoringCollector(context)
        val input = context.receive()
        val client = acquireClient(context.minionId)
        val response = try {
            client.execute(context, requestBuilder.requestFactory(context, input), monitoringCollector)
        } catch (e: Exception) {
            assignedClients.remove(context.minionId)
            tryAndLogOrNull(log) { client.close() }

            throw e.takeIf { it is SocketException } ?: SocketException(
                monitoringCollector.toResult(input, null, e.takeUnless { monitoringCollector.cause === e })
            )
        } finally {
            if (!shared && context.isTail) {
                assignedClients.remove(context.minionId)
                tryAndLogOrNull(log) { client.close() }
            }
        }

        val result = monitoringCollector.toResult(input, convertResponseToOutput(response), null)
        if (result.isFailure) {
            throw SocketRequestException(result)
        }
        context.send(result)
    }

    /**
     * Acquires the client assigned to the given minion, or assigns a pre-warmed one.
     */
    private fun acquireClient(minionId: MinionId): CLI {
        return assignedClients.computeIfAbsent(minionId) {
            preparedClients.poll() ?: error("No pre-warmed client available for minion $minionId")
        }
    }

    /**
     * Converts the response from the client into the output of the step.
     */
    @Suppress("UNCHECKED_CAST")
    open fun convertResponseToOutput(response: RES): O = response as O

    protected open fun createMonitoringCollector(context: StepContext<I, ConnectionAndRequestResult<I, O>>) =
        StepContextBasedSocketMonitoringCollector(context, eventsLogger, meterRegistry, stepQualifier)

    override suspend fun <IN> execute(
        monitoringCollector: StepContextBasedSocketMonitoringCollector,
        context: StepContext<*, *>,
        input: IN,
        request: REQ,
    ): RES {
        val client = acquireClient(context.minionId)
        return client.execute(context, request, monitoringCollector)
    }

    override fun keepOpen() = Unit

    override suspend fun close(minionId: MinionId) {
        assignedClients.remove(minionId)?.close()
    }

    override fun addUsage(count: Int) = Unit

    override suspend fun stop(context: StepStartStopContext) {
        running = false
        assignedClients.values.forEach { tryAndLogOrNull(log) { it.close() } }
        assignedClients.clear()

        preparedClients.forEach { tryAndLogOrNull(log) { it.close() } }
        preparedClients.clear()

        workerGroup.shutdownGracefully()
    }

    companion object {
        @JvmStatic
        private val log = logger()
    }
}
