name: Slack Plugin

on:
  push:
    branches: ['main', 'develop/*']
    paths: ['slack/**', 'buildSrc/**', 'build.gradle.kts', 'settings.gradle.kts', 'gradle.properties', 'gradle/**']
  pull_request:
    branches: ['main', 'develop/*']
    paths: ['slack/**', 'buildSrc/**', 'build.gradle.kts', 'settings.gradle.kts', 'gradle.properties', 'gradle/**']
  workflow_dispatch:

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  build-and-publish:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      module: qalipsis-plugin-slack
      module-dir: slack
    secrets: inherit

  verify-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_verify-pr.yml
    with:
      module: qalipsis-plugin-slack
      module-dir: slack
    secrets: inherit
